# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: '2.2.401'

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Restore"
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    displayName: "Dotnet Build"
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--no-restore --configuration $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: "Dotnet Publish"
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '-o $(Pipeline.Workspace)/publish --no-build'
  - task: PublishPipelineArtifact@1
    displayName: "Publish Artifacts"
    inputs:
      targetPath: '$(Pipeline.Workspace)/publish'
      artifact: 'web'
      publishLocation: 'pipeline'
  # - script: dotnet build ./SimplCommerce.sln
  #   displayName: 'dotnet build'
  # - script: ./run-tests.sh
  #   displayName: 'run tests'
  # - task: PublishTestResults@2
  #   displayName: 'Publish Test Results **/*.trx'
  #   condition: succeededOrFailed()
  #   inputs:
  #     testResultsFormat: VSTest
  #     testResultsFiles: '**/*.trx' 
  # - task: DotNetCoreCLI@2
  #   displayName: Publish
  #   inputs:
  #     command: publish
  #     publishWebProjects: True
  #     arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
  #     zipAfterPublish: True
  
  # - task: PublishBuildArtifacts@1
  #   displayName: 'Publish Artifact'
  #   inputs:
  #     PathtoPublish: '$(build.artifactstagingdirectory)'
  #   condition: succeededOrFailed()
  

# - job: Windows
#   pool:
#     vmImage: 'windows-2019'
#   steps:
#   - task: DotNetCoreInstaller@0
#     inputs:
#       packageType: 'sdk'
#       version: '2.2.401'
#   - script: dotnet build ./SimplCommerce.sln
#     displayName: 'dotnet build'
#   - task: PowerShell@2
#     inputs:
#       filePath: .\run-tests.ps1
#     displayName: 'run tests'
#   - task: PublishTestResults@2
#     displayName: 'Publish Test Results **/*.trx'
#     condition: succeededOrFailed()
#     inputs:
#       testResultsFormat: VSTest
#       testResultsFiles: '**/*.trx' 
